// WHY: @Injectable() marks this class as a "provider" that NestJS manages — it can be injected into other classes via dependency injection.
// WHY: The exception classes (UnauthorizedException, etc.) are NestJS's built-in HTTP error helpers — throwing one automatically sends the right HTTP status code and message.
import {
  Injectable,
  UnauthorizedException,   // WHY: throws 401 — used when credentials are wrong or token is invalid.
  ConflictException,       // WHY: throws 409 — used when something already exists (e.g. duplicate email).
  BadRequestException,     // WHY: throws 400 — used when the request is technically valid but logically wrong (e.g. store not found).
  NotFoundException,       // WHY: throws 404 — used when a requested resource doesn't exist in the database.
} from '@nestjs/common';

// WHY: JwtService is provided by NestJS's JWT library — it handles creating (signing) and verifying JWT tokens so we don't have to write that cryptography ourselves.
import { JwtService } from '@nestjs/jwt';

// WHY: bcrypt is a password hashing library — it turns a plain-text password into an irreversible hash so we never store raw passwords in the database.
import * as bcrypt from 'bcrypt';

// WHY: PrismaService is our database access layer — it gives us a type-safe API to query and update PostgreSQL without writing raw SQL.
import { PrismaService } from '../../prisma/prisma.service';

// WHY: RedisService wraps our Redis cache — we use Redis to track active sessions (refresh tokens) so we can instantly revoke them on logout.
import { RedisService } from '../../redis/redis.service';

// WHY: These are DTOs — plain classes whose properties define exactly what data this service expects to receive from the controller.
import { RegisterDto } from './dto/register.dto';
import { LoginDto } from './dto/login.dto';
import { UpdateProfileDto } from './dto/update-profile.dto';
import { ChangePasswordDto } from './dto/change-password.dto';

// WHY: Role is an enum generated by Prisma from the database schema — it ensures we only use valid role values (ADMIN, MANAGER, CASHIER).
import { Role } from '@prisma/client';

// WHY: @Injectable() tells NestJS's dependency injection system that this class can be instantiated and shared automatically across the app.
@Injectable()
export class AuthService {
  // WHY: NestJS automatically injects PrismaService, JwtService, and RedisService here — we declare what we need and NestJS provides them.
  constructor(
    private readonly prisma: PrismaService,    // WHY: used to read/write user data in the database.
    private readonly jwtService: JwtService,   // WHY: used to sign new JWTs and verify incoming tokens.
    private readonly redis: RedisService,      // WHY: used to track which refresh tokens are currently valid (for instant revocation on logout).
  ) {}

  // WHY: async means this function returns a Promise — we use await inside it to pause execution until database operations complete.
  async register(dto: RegisterDto) {
    // WHY: Check if a user with this email already exists for this store before creating — prevents duplicate accounts.
    const existing = await this.prisma.user.findUnique({
      // WHY: storeId_email is a Prisma composite unique key — the same email can exist in different stores, but not twice in the same store.
      where: { storeId_email: { storeId: dto.storeId, email: dto.email } },
    });
    // WHY: If a user is found, throw ConflictException (HTTP 409) — the email is already taken for this store.
    if (existing) throw new ConflictException('Email already registered for this store');

    // WHY: Verify the store actually exists before creating the user — we can't attach a user to a non-existent store.
    const store = await this.prisma.store.findUnique({ where: { id: dto.storeId } });
    if (!store) throw new BadRequestException('Store not found');

    // WHY: bcrypt.hash(password, 10) hashes the password with "salt rounds" = 10 — the higher the number, the harder it is to brute-force, but the slower it gets.
    const hashed = await bcrypt.hash(dto.password, 10);

    // WHY: prisma.user.create() inserts a new row into the users table — we store the hashed password, never the plain-text one.
    const user = await this.prisma.user.create({
      data: {
        storeId: dto.storeId,
        email: dto.email,
        password: hashed,        // WHY: storing the hash, not dto.password — raw passwords must never be stored.
        name: dto.name,
        role: dto.role || Role.CASHIER, // WHY: default to CASHIER if no role is provided — least-privilege principle.
      },
      // WHY: select limits which fields Prisma returns — we never return the password field, even the hashed version, to the client.
      select: { id: true, email: true, name: true, role: true, storeId: true, createdAt: true },
    });

    return { user, message: 'Registration successful' };
  }

  async login(dto: LoginDto) {
    // WHY: Look up the user by store + email combination — this is the unique identifier per store.
    const user = await this.prisma.user.findUnique({
      where: { storeId_email: { storeId: dto.storeId, email: dto.email } },
    });

    // WHY: !user handles "user doesn't exist" and !user.active handles "account was disabled" — both return the same generic error to avoid revealing whether an email is registered.
    if (!user || !user.active) throw new UnauthorizedException('Invalid credentials');

    // WHY: bcrypt.compare() hashes the provided password with the same salt stored in the hash and checks if they match — we can't decrypt the stored hash, only compare.
    const passwordMatch = await bcrypt.compare(dto.password, user.password);

    // WHY: If passwords don't match, throw 401 — same generic message to prevent revealing which part of the credentials was wrong.
    if (!passwordMatch) throw new UnauthorizedException('Invalid credentials');

    // WHY: generateTokens() creates both access token (short-lived) and refresh token (long-lived) for this user.
    const tokens = await this.generateTokens(user.id, user.email, user.role, user.storeId);

    // WHY: We store a hash of the refresh token in the database so we can verify it later and detect if it was tampered with.
    await this.prisma.user.update({
      where: { id: user.id },
      data: {
        refreshToken: await bcrypt.hash(tokens.refreshToken, 8), // WHY: salt rounds = 8 (slightly lower than password hash for speed, since refresh tokens are long random strings already).
        lastLoginAt: new Date(), // WHY: record the last login time for audit/security purposes.
      },
    });

    // WHY: Store a presence flag in Redis with a 7-day TTL — this lets us instantly revoke a token on logout by deleting the Redis key, even before the DB is checked.
    await this.redis.setRefreshToken(user.id, 7 * 24 * 60 * 60); // WHY: 7 * 24 * 60 * 60 = 604800 seconds = 7 days.

    return {
      accessToken: tokens.accessToken,   // WHY: the client uses this for every API request (short-lived, 15 min).
      refreshToken: tokens.refreshToken, // WHY: the client stores this safely to get a new access token when the old one expires (long-lived, 7 days).
      user: {
        id: user.id,
        email: user.email,
        name: user.name,
        role: user.role,
        storeId: user.storeId,
      },
    };
  }

  async refresh(refreshToken: string) {
    // WHY: try/catch wraps the whole function because jwtService.verify() throws an error if the token is expired or invalid — we catch it and return a clean 401.
    try {
      // WHY: jwtService.verify() checks the token's signature and expiry — if valid, it returns the decoded payload (sub, email, role, storeId).
      const payload = this.jwtService.verify(refreshToken, {
        // WHY: we must provide the refresh secret here — it's different from the access token secret so the two token types can't be swapped.
        secret: process.env.JWT_REFRESH_SECRET || 'fallback-refresh-secret',
      });

      // WHY: Look up the user to make sure their account still exists and is active — a token could be valid but the user might have been disabled since it was issued.
      const user = await this.prisma.user.findUnique({ where: { id: payload.sub } });
      if (!user || !user.active || !user.refreshToken) {
        throw new UnauthorizedException('Invalid refresh token');
      }

      // WHY: Compare the incoming refresh token with the hashed version stored in the DB — prevents using a stolen/old token after logout.
      const tokenMatch = await bcrypt.compare(refreshToken, user.refreshToken);
      if (!tokenMatch) throw new UnauthorizedException('Invalid refresh token');

      // WHY: Issue a brand-new pair of tokens (token rotation) — the old refresh token becomes invalid, improving security.
      const tokens = await this.generateTokens(user.id, user.email, user.role, user.storeId);

      // WHY: Update the stored refresh token hash with the new one — this invalidates the previous refresh token.
      await this.prisma.user.update({
        where: { id: user.id },
        data: { refreshToken: await bcrypt.hash(tokens.refreshToken, 8) },
      });

      // WHY: Reset the Redis TTL for another 7 days so the session stays alive as long as the user keeps refreshing.
      await this.redis.setRefreshToken(user.id, 7 * 24 * 60 * 60);

      return tokens;
    } catch {
      // WHY: Any error from verify() or our own throws is caught here and returned as a clean 401 — we never expose internal error details.
      throw new UnauthorizedException('Invalid or expired refresh token');
    }
  }

  async getMe(userId: string) {
    // WHY: Look up the user by their ID (extracted from the JWT's "sub" field by the JwtAuthGuard).
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      // WHY: select only the safe fields — never return the password hash, refresh token, or other sensitive columns to the client.
      select: { id: true, email: true, name: true, role: true, storeId: true, lastLoginAt: true, createdAt: true },
    });
    // WHY: Throw 404 if somehow the user ID from the token doesn't exist in the DB (e.g. user was deleted after token was issued).
    if (!user) throw new NotFoundException('User not found');
    return user;
  }

  async updateMe(userId: string, dto: UpdateProfileDto) {
    // WHY: Verify the user exists before attempting an update — avoids a confusing Prisma error if the record is missing.
    const user = await this.prisma.user.findUnique({ where: { id: userId } });
    if (!user) throw new NotFoundException('User not found');

    // WHY: prisma.user.update() applies only the fields present in the DTO — Prisma ignores undefined fields automatically.
    return this.prisma.user.update({
      where: { id: userId },
      data: dto,
      // WHY: select safe fields only — we don't want to accidentally expose the password hash in the response.
      select: { id: true, email: true, name: true, role: true, storeId: true },
    });
  }

  async changePassword(userId: string, dto: ChangePasswordDto) {
    // WHY: Fetch the full user record including the password hash so we can verify the current password.
    const user = await this.prisma.user.findUnique({ where: { id: userId } });
    if (!user) throw new NotFoundException('User not found');

    // WHY: Verify the current password — a user must prove they know their existing password before being allowed to change it (prevents someone who stole a session from changing the password).
    const match = await bcrypt.compare(dto.currentPassword, user.password);
    if (!match) throw new BadRequestException('Current password is incorrect');

    // WHY: Hash the new password before saving — we never store plain-text passwords.
    const hashed = await bcrypt.hash(dto.newPassword, 10);

    // WHY: Only update the password field — data: { password: hashed } leaves all other fields untouched.
    await this.prisma.user.update({ where: { id: userId }, data: { password: hashed } });
    return { message: 'Password changed successfully' };
  }

  async logout(userId: string) {
    // WHY: Set refreshToken to null in the database — this invalidates any refresh token the user had, so they can't get new access tokens.
    await this.prisma.user.update({
      where: { id: userId },
      data: { refreshToken: null },
    });

    // WHY: Also delete the Redis key — this provides a second layer of invalidation that works even before the DB check happens.
    await this.redis.revokeRefreshToken(userId);
    return { message: 'Logged out successfully' };
  }

  // WHY: private means this method is only used inside AuthService — it's an implementation detail not exposed to controllers.
  private async generateTokens(userId: string, email: string, role: string, storeId: string) {
    // WHY: The payload is the data encoded inside the JWT — the client can decode it (but not forge it) to know who they are without calling the server.
    const payload = { sub: userId, email, role, storeId }; // WHY: "sub" (subject) is the standard JWT field for the user's unique ID.

    // WHY: Promise.all() runs both sign operations concurrently — faster than awaiting them one after the other.
    const [accessToken, refreshToken] = await Promise.all([
      // WHY: signAsync(payload, options) creates a signed JWT — the secret is used to create a signature that only we can verify.
      this.jwtService.signAsync(payload, {
        secret: process.env.JWT_ACCESS_SECRET || 'fallback-secret',
        expiresIn: process.env.JWT_ACCESS_EXPIRES_IN || '15m', // WHY: short expiry (15 minutes) limits damage if an access token is stolen.
      }),
      this.jwtService.signAsync(payload, {
        secret: process.env.JWT_REFRESH_SECRET || 'fallback-refresh-secret', // WHY: different secret from access token — a refresh token cannot be used as an access token.
        expiresIn: process.env.JWT_REFRESH_EXPIRES_IN || '7d', // WHY: long expiry (7 days) so users don't need to log in every 15 minutes.
      }),
    ]);

    return { accessToken, refreshToken };
  }
}
