// WHY: We import specific HTTP method decorators from NestJS.
// Each decorator (@Get, @Post, @Patch) maps a class method to an HTTP route.
// e.g. @Get() means "when a GET request arrives, call this method".
import { Controller, Get, Post, Patch, Body, Param, Query, UseGuards } from '@nestjs/common';

// WHY: These Swagger decorators add documentation to the auto-generated API docs page
// at http://localhost:3001/api/docs — useful for testing endpoints without writing code.
import { ApiTags, ApiBearerAuth, ApiOperation } from '@nestjs/swagger';

// WHY: We import the service that contains the actual business logic.
// The controller's only job is to receive HTTP requests and delegate to the service.
import { OrdersService } from './orders.service';

// WHY: DTOs (Data Transfer Objects) define the shape of data that must arrive in the
// request body. NestJS validates incoming JSON against these shapes automatically.
import { CreateOrderDto } from './dto/create-order.dto';
import { UpdateOrderStatusDto } from './dto/update-order-status.dto';

// WHY: PaginationDto carries ?page=&limit=&search= query params so we can return
// data in small pages instead of dumping every single row at once.
import { PaginationDto } from '../../common/dto/pagination.dto';

// WHY: JwtAuthGuard checks that the incoming request has a valid Bearer token in its
// Authorization header. If the token is missing or expired, the request is rejected
// with 401 Unauthorized before it even reaches a controller method.
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';

// WHY: RolesGuard works together with @Roles() — after the JWT is verified it checks
// whether the logged-in user's role is allowed to call this specific route.
import { RolesGuard } from '../../common/guards/roles.guard';

// WHY: @Roles() is a custom decorator we use to declare which roles may access a route.
// RolesGuard reads this metadata at runtime and blocks everyone else.
import { Roles } from '../../common/decorators/roles.decorator';

// WHY: @StoreId() is a custom parameter decorator that reads the storeId field from
// the decoded JWT payload. This means we never trust a storeId sent by the client —
// it always comes from the verified token, preventing users from reading other stores' data.
import { StoreId } from '../../common/decorators/store-id.decorator';

// WHY: @CurrentUser() is a custom parameter decorator that extracts the full decoded
// JWT payload so we can know WHO is making the request (e.g., the cashier's user ID).
import { CurrentUser } from '../../common/decorators/current-user.decorator';

// WHY: JwtPayload is a TypeScript interface that describes the shape of our decoded
// JWT — gives us type safety so we can't mistype field names like user.sub.
import { JwtPayload } from '../../common/interfaces/jwt-payload.interface';

// WHY: Role and OrderStatus are enums generated by Prisma directly from the database
// schema. Using them instead of plain strings prevents typos like "ADMIN" vs "Admin".
import { Role, OrderStatus } from '@prisma/client';

// WHY: @ApiTags groups all routes in this controller under an "orders" section in Swagger docs.
@ApiTags('orders')

// WHY: @ApiBearerAuth tells Swagger that every route here requires an Authorization: Bearer <token> header.
// This enables the "Authorize" button in Swagger UI so you can test protected routes.
@ApiBearerAuth('access-token')

// WHY: @UseGuards at the class level means EVERY route in this controller runs these two guards.
// JwtAuthGuard verifies the token first; RolesGuard then checks the role.
// We don't have to repeat this on each method.
@UseGuards(JwtAuthGuard, RolesGuard)

// WHY: @Controller('orders') sets the URL prefix. Every route in this class lives under /api/v1/orders.
@Controller('orders')
export class OrdersController {
  // WHY: This is Dependency Injection (DI). Instead of writing `new OrdersService()` ourselves,
  // we declare what we need and NestJS creates and injects the instance for us.
  // This makes the code easier to test and avoids creating multiple instances of the same service.
  constructor(private readonly ordersService: OrdersService) {}

  // WHY: @Get() with no arguments maps to GET /api/v1/orders
  // This is the "list all orders" endpoint.
  @Get()
  // WHY: @ApiOperation adds a human-readable description to this route in Swagger docs.
  @ApiOperation({ summary: 'List orders with filtering' })
  findAll(
    // WHY: @StoreId() reads the storeId from the JWT so we only return orders that
    // belong to the store the logged-in user works at — not every order in the database.
    @StoreId() storeId: string,

    // WHY: @Query() without a key name maps ALL query string params (?page=&limit=&search=)
    // into the PaginationDto object at once, with automatic validation.
    @Query() dto: PaginationDto,

    // WHY: @Query('status') picks out just the ?status= query param separately
    // because it is optional — we only filter by status when the caller provides it.
    @Query('status') status?: OrderStatus,
  ) {
    // WHY: We spread dto and add status into one object so the service receives
    // all filter options in a single parameter.
    return this.ordersService.findAll(storeId, { ...dto, status });
  }

  // WHY: @Get(':id') maps to GET /api/v1/orders/:id — the colon makes :id a URL variable.
  // e.g. GET /api/v1/orders/abc-123 → id = "abc-123"
  @Get(':id')
  @ApiOperation({ summary: 'Get order by ID' })
  findOne(
    @StoreId() storeId: string,

    // WHY: @Param('id') extracts the :id segment from the URL path and gives it to us
    // as a string named 'id'.
    @Param('id') id: string,
  ) {
    return this.ordersService.findOne(storeId, id);
  }

  // WHY: @Post() maps to POST /api/v1/orders — the standard way to create a new resource.
  @Post()
  @ApiOperation({ summary: 'Create a new order' })
  create(
    @StoreId() storeId: string,

    // WHY: @CurrentUser() gives us the logged-in user object from the JWT.
    // We need user.sub (the user's database ID) to record who the cashier is on this order.
    @CurrentUser() user: JwtPayload,

    // WHY: @Body() extracts the entire JSON request body and validates it against CreateOrderDto.
    // If any required field is missing or has the wrong type, NestJS rejects the request
    // with a 400 Bad Request before this method even runs.
    @Body() dto: CreateOrderDto,
  ) {
    // WHY: user.sub is the "subject" claim of the JWT — it holds the cashier's user ID.
    // We pass it so the order is linked to the correct employee.
    return this.ordersService.create(storeId, user.sub, dto);
  }

  // WHY: @Patch(':id/status') maps to PATCH /api/v1/orders/:id/status
  // PATCH means a partial update — we're only changing the status field, not the whole order.
  @Patch(':id/status')

  // WHY: @Roles() restricts this route to ADMIN and MANAGER only.
  // A cashier can create orders but should not be able to cancel or complete them manually.
  // RolesGuard will return 403 Forbidden for any other role.
  @Roles(Role.ADMIN, Role.MANAGER)

  @ApiOperation({ summary: 'Update order status (triggers stock deduction on COMPLETED)' })
  updateStatus(
    @StoreId() storeId: string,
    @Param('id') id: string,
    @Body() dto: UpdateOrderStatusDto,
  ) {
    return this.ordersService.updateStatus(storeId, id, dto);
  }
}
