// WHY: We import specific building blocks from NestJS. Each one has a job:
//   - Controller  → marks this class as an HTTP route handler
//   - Get/Post/Patch → decorators that map a method to an HTTP verb (GET, POST, PATCH)
//   - Body        → pulls the JSON payload out of the incoming request body
//   - Param       → pulls a value out of the URL path, e.g. /users/:id → id
//   - UseGuards   → attaches security checks ("guards") that run before the handler
import { Controller, Get, Post, Patch, Body, Param, UseGuards } from '@nestjs/common';

// WHY: Swagger decorators add documentation to every endpoint automatically.
//   - ApiTags      → groups routes under a named section in the Swagger UI
//   - ApiBearerAuth → tells Swagger this route needs a Bearer token in the header
//   - ApiOperation  → gives a human-readable summary for each endpoint
import { ApiTags, ApiBearerAuth, ApiOperation } from '@nestjs/swagger';

// WHY: UsersService is where the actual database logic lives.
//   The controller only handles HTTP — it delegates all real work to the service.
import { UsersService } from './users.service';

// WHY: CreateUserDto (Data Transfer Object) defines the exact shape of the JSON body
//   that must be sent when creating a user. NestJS validates it automatically.
import { CreateUserDto } from './dto/create-user.dto';

// WHY: JwtAuthGuard checks that the incoming request has a valid JWT access token.
//   Without this, anyone on the internet could call these endpoints.
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';

// WHY: RolesGuard works together with @Roles() below.
//   It reads which roles are allowed for a route and blocks requests from users
//   whose role doesn't match. e.g. a Cashier cannot create users.
import { RolesGuard } from '../../common/guards/roles.guard';

// WHY: @Roles() is a decorator we attach to a route to declare which roles may use it.
//   Behind the scenes it sets "metadata" that RolesGuard reads at runtime.
import { Roles } from '../../common/decorators/roles.decorator';

// WHY: @StoreId() is a custom parameter decorator. It reads the storeId that was
//   embedded inside the JWT when the user logged in, so we never trust the client
//   to send storeId in the request body — it always comes from the verified token.
import { StoreId } from '../../common/decorators/store-id.decorator';

// WHY: Role is the enum generated by Prisma from the database schema.
//   Values: Role.ADMIN, Role.MANAGER, Role.CASHIER
//   Using the enum (not raw strings like "ADMIN") means TypeScript will catch typos.
import { Role } from '@prisma/client';

// WHY: @ApiTags('users') groups all routes in this controller under "users"
//   in the Swagger docs at http://localhost:3001/api/docs
@ApiTags('users')

// WHY: @ApiBearerAuth('access-token') tells Swagger that every route here needs
//   a Bearer token. This makes the "Authorize" button in Swagger UI work.
@ApiBearerAuth('access-token')

// WHY: @UseGuards(JwtAuthGuard, RolesGuard) applies both guards to EVERY route
//   in this entire controller. Guards run in order — JWT check first, then role check.
//   This means you don't have to repeat @UseGuards on every single method.
@UseGuards(JwtAuthGuard, RolesGuard)

// WHY: @Controller('users') registers this class as the handler for all routes
//   that start with /api/v1/users (the /api/v1 prefix is set globally in main.ts).
@Controller('users')
export class UsersController {

  // WHY: NestJS uses "dependency injection" — instead of writing `new UsersService()`
  //   we declare it as a constructor parameter and NestJS creates and provides it for us.
  //   `private readonly` means this.usersService is available everywhere in the class
  //   but cannot be replaced or accidentally changed.
  constructor(private readonly usersService: UsersService) {}

  // WHY: @Get() with no path matches GET /api/v1/users — lists all users.
  @Get()
  // WHY: @Roles(Role.ADMIN, Role.MANAGER) means only ADMINs and MANAGERs can call
  //   this route. A CASHIER token will get a 403 Forbidden response.
  @Roles(Role.ADMIN, Role.MANAGER)
  // WHY: @ApiOperation adds a one-line description that shows up in Swagger UI.
  @ApiOperation({ summary: 'List all users in the store' })
  // WHY: @StoreId() extracts the storeId from the JWT (set during login).
  //   This ensures users only ever see data from their own store.
  findAll(@StoreId() storeId: string) { return this.usersService.findAll(storeId); }

  // WHY: @Get(':id') matches GET /api/v1/users/some-uuid-here
  //   The `:id` is a route parameter — a placeholder for any value in that URL position.
  @Get(':id')
  // WHY: Managers need to look up individual user details too, so both roles allowed.
  @Roles(Role.ADMIN, Role.MANAGER)
  @ApiOperation({ summary: 'Get a user by ID' })
  // WHY: @Param('id') reads the `:id` placeholder from the URL and passes it as the
  //   `id` argument. So GET /users/abc123 gives id = "abc123".
  findOne(@StoreId() storeId: string, @Param('id') id: string) {
    return this.usersService.findOne(storeId, id);
  }

  // WHY: @Post() matches POST /api/v1/users — creates a new user.
  @Post()
  // WHY: Only ADMINs can create new users. Managers can view but not add staff.
  @Roles(Role.ADMIN)
  @ApiOperation({ summary: 'Create a new user' })
  // WHY: @Body() pulls the JSON body from the POST request and maps it to CreateUserDto.
  //   NestJS will automatically validate it (required fields, correct types, etc.).
  create(@StoreId() storeId: string, @Body() dto: CreateUserDto) {
    return this.usersService.create(storeId, dto);
  }

  // WHY: @Patch(':id') matches PATCH /api/v1/users/some-uuid — partial update.
  //   PATCH means "update only the fields you send", unlike PUT which replaces everything.
  @Patch(':id')
  // WHY: Only ADMINs can change user details (name, role, password, etc.).
  @Roles(Role.ADMIN)
  @ApiOperation({ summary: 'Update a user' })
  // WHY: `Partial<CreateUserDto>` means all fields from CreateUserDto are now optional.
  //   You can send just { "name": "Alice" } without providing email or password.
  update(@StoreId() storeId: string, @Param('id') id: string, @Body() dto: Partial<CreateUserDto>) {
    return this.usersService.update(storeId, id, dto);
  }

  // WHY: @Patch(':id/toggle') matches PATCH /api/v1/users/some-uuid/toggle
  //   This is a dedicated "sub-action" route — it flips a user's active/inactive status.
  //   Using a named sub-route (/toggle) makes the intent very clear.
  @Patch(':id/toggle')
  // WHY: Only ADMINs can deactivate or reactivate staff accounts.
  @Roles(Role.ADMIN)
  @ApiOperation({ summary: 'Toggle user active status' })
  toggle(@StoreId() storeId: string, @Param('id') id: string) {
    return this.usersService.toggleActive(storeId, id);
  }
}
